name: flutter_tts_example
description: Demonstrates how to use the flutter_tts plugin.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_tts:
    path: ../

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.12.0-0 <3.0.0'
